//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelFileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class StudentsList
    //{
       
    //}



    public class StudentsList
    {
        public int RollNumber { get; set; }
        public string Student_Name { get; set; }
        public Nullable<int> Hindi { get; set; }
        public Nullable<int> English { get; set; }
        public Nullable<int> Physics { get; set; }
        public Nullable<int> Chemistry { get; set; }
        public Nullable<int> Biology { get; set; }
        public Nullable<int> Mathematics { get; set; }

    }
    //public static class TestJsonDotNetValueProviderFactoryModelExtensions
    //{
    //    public static TestJsonDotNetValueProviderFactoryModel LoadTestData(this TestJsonDotNetValueProviderFactoryModel model)
    //    {
    //        model.RollNumber = false;
    //        model.Student_Name = char.Parse("A");
    //        model.DateTimeProperty = DateTime.MaxValue.ToString("yyyy/MM/dd");
    //        model.DecimalProperty = decimal.MaxValue;
    //        model.FloatProperty = float.MaxValue;
    //        model.IntProperty = int.MaxValue;
    //        model.LongProperty = long.MaxValue;
    //        model.ShortProperty = short.MaxValue;
    //        model.StringProperty = "StringProperty value";
    //        model.UintProperty = uint.MaxValue;
    //        model.UlongProperty = ulong.MaxValue;
    //        model.UshortProperty = ushort.MaxValue;

    //        return model;
    //    }

    //}
}
